import Head from "next/head";
import Image from "next/image";

//images
import profileImage from "../public/pp3.jpg";
import projectimage1 from "../public/bmi.png";
import chembot from "../public/chem_chatbot.png";
import tCCweb from "../public/TCC_web.jpeg";
import moraweb from "../public/mora_web.png";
import portfolio from "../public/portfolio_site.png";
import sltc from "../public/SLTC.png";
import scl from "../public/rvc.png";
import webskill from "../public/app-development.png";
import mlskill from "../public/machine-learning_icon.png";
import cloudskill from "../public/cloud_icon.png";
import lapweb from "../public/lap_price.png";

//framer
import {motion} from "framer-motion"

//icons
import {BsFillMoonStarsFill} from "react-icons/bs"
import{AiOutlineGithub,AiFillLinkedin,AiOutlineTwitter} from "react-icons/ai"

//hooks
import {useState} from "react"




export default function Home() {

  const [darkmode, setdarkmode] = useState(false)
  return (
  
    <div className={darkmode? "dark" : ""}>

      <Head>
        <title>Portfolio website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />


        <style>
            @import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
        </style>
      </Head>
      
        
      <main className="font-poppins bg-white min-h-screen px-10 md:px-20 lg:px-40 dark:bg-black" >

        {/* nav hero */}
        <section>
          {/* nav */}
          <nav className="py-10 flex justify-between">
            <h1 className="text-sm md:text-sm dark:text-white">Developed by Dinisuru Maduhansa</h1>

            <ul className="flex items-center">
              {/* icon */}
              <li>
              <BsFillMoonStarsFill onClick={() => setdarkmode(!darkmode)} className="cursor-pointer text-xl mx-5 dark:text-white" />
              </li>
              <li>
                <a href="https://drive.google.com/file/d/1WLzCPoaQ8GLl0BsatJXghFSrb0PI9yg7/view?usp=sharing" className=" bg-yellow-400 text-black px-4 py-2 border-none rounded-md">Resume</a>
              </li>
            </ul>

          </nav>


          {/* hero */}
          <div className="text-center p-10">
            <h1 className="text-5xl font-bold text-teal-600 md:text-6xl lg:text-7xl">Dinisuru Maduhansa</h1>
            <h3 className="text-2xl py-4 md:text-3xl dark:text-white">Software Engineering Undergraduate</h3>
            <p className="text-sm py-4 text-gray-500 leading-6 max-w-xl mx-auto md:text-md dark:text-white">
            Welcome to my portfolio! I'm excited to share my journey as I look for a software development internship. 
            I have experience in web and mobile app development,and I'm also interested in <b>DevOps</b> . 
            I'm always eager to learn and work on new projects. Check out my work to see how I bring creativity and problem-solving to the table. 
            Let's connect and see how we can work together!
            </p>
          </div>
          {/* socials */}
          <div className="text-5xl flex justify-center gap-16 text-gray-600">
            <a href="https://github.com/topicrecorder?tab=repositories" aria-label="github"><AiOutlineGithub /></a>
            <a href="www.linkedin.com/in/dinisuru-maduhansa-b9ba44308" aria-label="linkedin"><AiFillLinkedin /></a>
            <a href="#" aria-label="twitter"><AiOutlineTwitter /></a>


          </div>
          {/* profile */}
          <motion.div
          initial={{opacity: 0 , scale: 0.5}}
          animate={{opacity: 1, scale: 1}}
          transition={{duration: 0.5}}
          >
          <div className="m-auto relative  w-80 h-80 p-5 mt-20 rounded-full overflow-hidden">

            <Image src={profileImage} alt="profile image" layout="fill" objectFit="cover" />


          </div>
          </motion.div>


        </section>

        
        <section className="py-20">
          <div >
            <h2 className="text-gray-950 text-5xl py-10 pt-20 font-bold opacity-60 dark:text-white">Projects</h2>

          </div>
          {/* projects cards */}
          <div className="flex flex-col gap-8 p-8 sm:grid sm:grid-cols-1 md:grid md:grid-cols-3 lg:grid lg:grid-cols-3 lg:gap-10">
            {/* project card 1 */}
            <motion.div whileHover={{scale: 1.1}} whileTap={{scale: 0.9}}>
            <div className="bg-slate-50 shadow-md p-5 rounded-xl my-6 h-full flex flex-col justify-between ">
              <div className="w-full h-64 overflow-hidden flex justify-center items-center ">
              <Image src={chembot} alt="chem_bot" width={400} height={400} className="object-cover pb-9 " />
              </div>
              
              <h2 className="text-xl font-bold py-1 text-left ">Tutoring Chatbot</h2>
              <p className="text-sm py-2 text-gray-700 leading-6 text-left">
              The goal of this project is to create an AI-powered chatbot that provides personalized and comprehensive tutoring for A/L chemistry students in Sri
              Lanka. This innovative tool aims to simplify complex concepts, assist with
              problem-solving, and enhance exam preparation, ultimately improving
              students' understanding and performance in chemistry

              </p>
              <p className="text-sm py-2 text-gray-700 leading-6 text-left" > Technologies used : LangChain, OpenAI API,
              Machine Learning Framework</p>
              <div className="text-3xl flex justify-center gap-16 text-gray-600">
              <a href="https://github.com/topicrecorder/BMI-Calculator-Final-project" aria-label="github"><AiOutlineGithub /></a>

              </div>
              
            </div>
            </motion.div>
            {/* project card 2 */}

            <motion.div whileHover={{scale: 1.1}} whileTap={{scale: 0.9}}>
            <div className="bg-slate-50 shadow-md p-5 rounded-xl my-6 h-full flex flex-col justify-between ">
              <div className="w-full h-64 overflow-hidden flex justify-center items-center ">
              <Image src={tCCweb} alt="tCC_web" width={400} height={400} className="object-cover pb-8 " />
              </div>
              
              <h2 className="text-xl font-bold py-2 text-left ">Time Table Management System (group)</h2>
              <p className="text-sm py-2 text-gray-700 leading-6 text-left">
              The project involves designing a software application that automates the
              creation of time tables. The application should consider constraints like teacher
              availability, room capacity, subject requirements, and avoid conflicts.
              Additionally, it should optimize the schedule for efficient use of resources and
              user defined preferences.

              </p>
              <p className="text-sm py-2 text-gray-700 leading-6 text-left"> Technologies used :  Python, Django,</p>
              <div className="text-3xl flex justify-center gap-16 text-gray-600">
              <a href="https://github.com/topicrecorder/BMI-Calculator-Final-project" aria-label="github" className="pt-4"><AiOutlineGithub /></a>

              </div>
              
            </div>
            </motion.div>

            {/* project card 3 */}

            <motion.div whileHover={{scale: 1.1}} whileTap={{scale: 0.9}}>
            <div className="bg-slate-50 shadow-md p-5 rounded-xl my-6 h-full flex flex-col justify-between ">
              <div className="w-full h-64 overflow-hidden flex justify-center items-center ">
              <Image src={moraweb} alt="BMI image" width={400} height={400} className="object-cover pb-8 " />

              </div>
              
              <h2 className="text-xl font-bold py-2 text-left ">Business Guide Website</h2>
              <p className="text-sm py-2 text-gray-700 leading-6 text-left">
              where innovation meets functionality! This website is designed with a user-friendly interface that ensures a seamless experience across all devices.
               Featuring a sticky navigation bar, you can effortlessly explore our content and services without losing your place on the page.
              </p>
              <br />
              <p className="text-sm py-2 text-gray-700 leading-6 text-left"> Technologies used :   HTML, CSS</p>
              <div className="text-3xl flex justify-center gap-16 text-gray-600">
              
              <a href="https://github.com/topicrecorder/BMI-Calculator-Final-project" aria-label="github" className="pt-4"><AiOutlineGithub /></a>

              </div>
              
            </div>
            </motion.div>

            {/* project card 4 */}

            <motion.div whileHover={{scale: 1.1}} whileTap={{scale: 0.9}}>
            <div className="bg-slate-50 shadow-md p-5 rounded-xl my-6 h-full flex flex-col justify-between ">
              <div className="w-full h-64 overflow-hidden flex justify-center items-center ">
              <Image src={portfolio} alt="portfolio_web" width={400} height={400} className="object-cover pb-8 " />

              </div>
              
              <h2 className="text-xl font-bold py-2 text-left ">Portfolio Website</h2>
              <p className="text-sm py-2 text-gray-700 leading-6 text-left">
              I build a modern and professional portfolio website in 2024 .
              I built my portfolio website using React for the frontend, Tailwind CSS for styling to
              create a responsive and user-friendly website showcasing my skills and work.

              </p>
              <br />
              <p className="text-sm py-2 text-gray-700 leading-6 text-left"> Technologies used : React, Tailwind CSS</p>
              <div className="text-3xl flex justify-center gap-16 text-gray-600">
              <a href="https://github.com/topicrecorder/BMI-Calculator-Final-project" aria-label="github" className="pt-7"><AiOutlineGithub /></a>

              </div>
              
            </div>
            </motion.div>

            {/* project card 5 */}

            <motion.div whileHover={{scale: 1.1}} whileTap={{scale: 0.9}}>
            <div className="bg-slate-50 shadow-md p-5 rounded-xl my-6 h-full flex flex-col justify-between ">
              <div className="w-full h-64 overflow-hidden flex justify-center items-center ">
              <Image src={lapweb} alt="lap price" width={200} height={300} className="object-cover " />

              </div>
              
              <h2 className="text-xl font-bold py-2 text-left ">Laptop Price Predictor
              </h2>
              <p className="text-sm py-2 text-gray-700 leading-6 text-left">
              Laptop Price Predictor is a machine learning-based web application built using a Flask server.
              It predicts the price of laptops based on user input, such as specifications and features. 
              This project showcases the integration of machine learning models with a web interface to deliver real-time price predictions

              </p>
              <p className="text-sm py-2 text-gray-700 leading-6 text-left"> Technologies used : Flask,scikit-learn,HTML, CSS</p>
              <div className="text-3xl flex justify-center gap-16 text-gray-600">
              <a href="https://github.com/topicrecorder/BMI-Calculator-Final-project" aria-label="github"><AiOutlineGithub /></a>

              </div>
              
            </div>
            </motion.div>

            {/* project card 6 */}

            <motion.div whileHover={{scale: 1.1}} whileTap={{scale: 0.9}}>
            <div className="bg-slate-50 shadow-md p-5 rounded-xl my-6 h-full flex flex-col justify-between ">
              <div className="w-full h-64 overflow-hidden flex justify-center items-center ">
              <Image src={projectimage1} alt="BMI image" width={300} height={300} className="object-cover " />

              </div>
              
              <h2 className="text-xl font-bold py-2 text-left ">BMI Calculator</h2>
              <p className="text-sm py-2 text-gray-700 leading-6 text-left">
              BMI, or Body Mass Index, is a numerical value of a person's weight in relation to their height. It is a commonly used 
              screening tool to categorize individuals into different weight status categories, such as underweight, normal weight, 
              overweight, and obesity.This flutter application can calculate BMI using Material UI and GetX.

              </p>
              <p className="text-sm py-2 text-gray-700 leading-6 text-left"> Technologies used : Dart, Flutter, GetX</p>
              <div className="text-3xl flex justify-center gap-16 text-gray-600">
              <a href="https://github.com/topicrecorder/BMI-Calculator-Final-project" aria-label="github"><AiOutlineGithub /></a>

              </div>
              
            </div>
            </motion.div>

          </div>


        </section>

        {/* skills */}
        <section>
          <div >
            <h2 className="text-gray-950 text-5xl py-10 font-bold opacity-60 dark:text-white">Specialities</h2>

          </div>
          {/* projects cards */}
          <div className="flex flex-col gap-8 p-8 sm:grid sm:grid-cols-1 md:grid md:grid-cols-3 lg:grid lg:grid-cols-3 lg:gap-10">
            {/* project card 1 */}
            <motion.div whileHover={{scale: 1.1}} whileTap={{scale: 0.9}}>
            <div className="bg-slate-50 shadow-md p-5 rounded-xl my-6 h-full flex flex-col justify-between ">
              <div className="w-full flex justify-center ">
              <Image src={webskill} alt="web development" width={100} height={100} className="inline pt-5" />
              </div>
              
              <h2 className="text-xl font-bold pt-5 text-center ">Web Development</h2>
              <p className="text-sm py-2 text-gray-800 leading-6 text-left">
              Experienced in building responsive, user-friendly websites using modern web technologies like <b>HTML, CSS, JavaScript, and React</b> . 
              Skilled in both front-end and back-end development, with a focus on creating clean, efficient code and seamless user experiences.
               Adept at working with frameworks and libraries to bring web designs to life.

              </p>
              
            </div>
            </motion.div>
            {/* project card 2 */}

            <motion.div whileHover={{scale: 1.1}} whileTap={{scale: 0.9}}>
            <div className="bg-slate-50 shadow-md p-5 rounded-xl my-6 h-full flex flex-col justify-between ">
              <div className="w-full flex justify-center ">
              <Image src={mlskill} alt="machine learning" width={100} height={100} className="inline pt-5" />
              </div>
              
              <h2 className="text-xl font-bold pt-5 text-center ">Machine Learning</h2>
              <p className="text-sm py-2 text-gray-800 leading-6 text-left">
              I have foundational knowledge in machine learning, focusing on data preprocessing, basic model building, and performance evaluation. 
              I am familiar with key algorithms such as <b>linear regression</b>  and <b>decision trees , random forests</b>, 
              and have experience working with Python libraries like <b>TensorFlow</b> and <b>scikit-learn</b> to develop simple predictive models.

              </p>

              
            </div>
            </motion.div>

            {/* project card 3 */}
            <motion.div whileHover={{scale: 1.1}} whileTap={{scale: 0.9}}>
            <div className="bg-slate-50 shadow-md p-5 rounded-xl my-6 h-full flex flex-col justify-between ">
              <div className="w-full flex justify-center ">
              <Image src={cloudskill} alt="cloud" width={100} height={100} className="inline pt-5" />

              </div>
              
              <h2 className="text-xl font-bold pt-5 text-center ">Cloud Computing</h2>
              <p className="text-sm py-2 text-gray-800 leading-6 text-left pb-8">
              Familiar with cloud computing concepts and services, including <b>AWS</b> . Experienced in deploying and managing applications in the cloud, 
              with a solid understanding of cloud infrastructure, scalability, and security. 
              Eager to expand knowledge and apply cloud technologies to optimize system performance.

              </p>

              
            </div>
            </motion.div>
          </div>


        </section>
        {/* Education */}
        <section>
          <div >
            <h2 className="text-gray-950 text-5xl py-10 font-bold opacity-60 dark:text-white">Education</h2>

          </div>
          {/* projects cards */}
          <div className="flex flex-col gap-8 p-8 lg:grid  lg:grid-cols-2 lg:gap-6 ">
            {/* project card 1 */}
            <div className="bg-slate-50  shadow-md p-5 rounded-xl my-6 lg:h-90 md:h-72">
              <div className="w-full flex justify-end  ">
              <Image src={sltc} alt="campus" width={200} height={200} className="inline" />
              </div>
              
              <h2 className="text-3xl font-bold py-7 text-left ">SLTC Research University </h2>
              <p className="text-md  text-gray-800  text-left">
              BSc (Hons) in Software Engineering | 4th Year Undergraduate

              </p>
            </div>
            <div className="bg-slate-50  shadow-md p-5 rounded-xl my-6 lg:h-90 md:h-72">
              <div className="w-full flex justify-end ">
              <Image src={scl} alt="school" width={100} height={100} className="inline" />
              </div>
              
              <h2 className="text-3xl font-bold py-2 text-left ">H/Ruhunu Vijayaba College</h2>
              <p className="text-sm py-2 text-gray-800 leading-6 text-left">
              In 2020, I completed the GCE Advanced Level in the Physical Science stream

              </p>
              
              
            </div>
          </div>


        </section>

              <footer className="">
                  <div className="w-full flex-col px-6 pt-20 lg:flex lg:px-10 xl:px-24">
                      <div className="text-zinc-600 cursor-default lg:flex lg:flex-row lg:gap-x-16">
                        <div>
                            <h2 className="text-2xl text-zinc-800 font-mono font-bold dark:text-white">Dinisuru Maduhansa</h2>
                            <ul className="mt-4 text-sm flex flex-col items-start justify-start gap-2">
                              <li className="flex flex-row items-start">
                                <span ><svg aria-hidden="true" viewBox="0 0 1024 1024" className="w-4 h-4 mr-1 mt-1 fill-zinc-600" preserveAspectRatio="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M517.802667 612.181333c96.298667-5.12 152.874667-91.946667 181.205333-168.704 45.226667-10.154667 45.226667-71.552 11.349333-97.109333 8.021333-79.744 34.816-194.090667-65.28-198.314667-27.093333-1.109333-43.093333-26.496-145.834666-18.474666-62.592 5.034667-125.056 15.104-163.712 49.450666-39.594667 35.2-37.248 103.296-27.093334 172.458667-34.048 20.48-22.741333 81.834667 22.570667 97.152 28.288 76.629333 90.538667 168.618667 186.794667 163.541333z m114.133333 17.834667c-31.232 58.154667-49.066667 126.848-80.298667 179.669333-4.437333-36.992-3.84-61.269333-4.437333-137.386666h-75.776c4.437333 95.146667 4.437333 95.146667-4.522667 137.386666-22.314667-58.112-44.544-126.805333-75.776-179.626666-133.717333 21.12-231.850667 84.522667-236.245333 264.192h713.386667c-0.085333-179.669333-102.656-243.072-236.373334-264.234667z"></path></svg></span>
                              <p className="font-inter dark:text-white">076 7006719</p>
                            </li>
                            <li className="flex flex-row items-start">
                              <span>
                                <svg aria-hidden="true" viewBox="0 0 1024 1024" className="w-4 h-4 mr-1 mt-1 fill-zinc-600" preserveAspectRatio="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M513.2 898.3c-106.4 0-206.6-9.2-282.3-26.1-88.9-19.9-137.4-47.5-132-83.3 3.7-25 19.5-37.2 58.5-51.6 32.6-12 96.8-27.2 148.5-35.6 12-2 21.4 5.4 23.4 17.3 2 12-6.4 21-18.3 23-44.4 7.2-105.8 20.8-132 31.2-29 11.5-26.2 14.8-26.2 17 0 1.8 0.6 8.9 20.4 18.2 19.2 9 47 17.4 80.4 24.5 71.7 15 165.6 23.3 264.7 23.3 99 0 193-8.3 264.7-23.3 33.5-7 61.3-15.5 80.4-24.5 19.9-9.2 16.2-16.2 17-17.8-1-2-3.7-5.9-32.7-17.3-26.2-10.4-82.4-23.7-126.7-30.9-12-2-20.3-10.3-18.4-22.3 2-12 12.4-20.3 24.4-18.4 51.7 8.3 109 24.3 142 35.5 39.3 13.3 54.8 26.6 58.6 51.8 5.4 35.8-43.2 63.5-132.2 83.2-75.6 16.9-175.8 26.1-282.2 26.1z"></path><path fill-rule="evenodd" clip-rule="evenodd" d="M510.8 98.2c-134.1 0-239.5 108.4-239.3 242.4 0 4 0.1 8.2 0.3 12.3 1.4 28.6 10.2 57.2 21.4 83.4v0.1l17.9 34.5c1.5 2.9 148.7 277.2 165.1 303.1 9.2 14.5 24.6 20.7 35.5 20.7 10.6 0 27.6-5.7 35.3-20.7 12.3-24 175.8-303.1 175.8-303.1s15.2-26.2 18.7-34.6c13.4-31.7 18.9-49.2 20.3-83.7 0.1-3.6 0.2-9.4 0.2-12.3C761.9 206 644.9 98.2 510.8 98.2z m2.4 368.9c-74.2 0-134.3-60.1-134.3-134.3 0-74.2 60.1-134.3 134.3-134.3 74.2 0 134.3 60.1 134.3 134.3 0 74.2-60.1 134.3-134.3 134.3z"></path></svg>
                              </span>
                              <p className="font-inter dark:text-white">41/B/1, Indipittaniya, Waharakgoda, Beliatta.</p>
                            </li>
                          </ul>
                        </div>
                        <div className="mt-4 md:mt-0 lg:mt-0 flex flex-row flex-wrap lg:flex-nowrap lg:justify-center gap-4 lg:gap-x-24">
                          <div className="flex flex-col">
                            <h2 className="font-mono font-bold text-zinc-700 text-lg dark:text-white">Contact</h2>
                            <ul className="mt-4 grid gap-2 ">
                              <li className="flex items-start text-sm">
                                <span><svg aria-hidden="true" viewBox="0 0 1024 1024" className="w-4 h-4 mr-1 mt-1 fill-zinc-600" preserveAspectRatio="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M702.229 505.85l257.369 208.406V297.444zM599.854 588.749c-25.344 20.528-56.423 30.791-87.498 30.791-31.08 0-62.155-10.264-87.513-30.796l-53.778-43.556L65.846 792.386c2.945 22.208 13.831 41.923 29.75 56.193 7.592 6.805 16.341 12.319 25.868 16.329 10.846 4.566 22.712 7.164 35.207 7.164h711.225c15.817 0 30.632-4.139 43.612-11.24 9.122-4.99 17.365-11.399 24.295-19.056 12.221-13.502 20.449-30.628 22.931-49.554l-305.078-247.04-53.802 43.567zM64.969 297.272v417.157l257.529-208.577z"></path><path fill-rule="evenodd" clip-rule="evenodd" d="M419.633 505.853l43.688 35.383c28.408 23.005 69.652 23.005 98.061 0l43.699-35.386 48.574-39.333 303.38-245.664c-9.591-40.379-45.87-70.543-89.139-70.543H156.671c-43.219 0-79.46 30.093-89.103 70.4l303.497 245.807 48.568 39.336z">
                                  </path>
                                  </svg>
                                  </span>
                                  <a href="mailto:dinisurumad@gmail.com" className="text-left text-zinc-600 break-words hover:underline hover:text-zinc-800 dark:text-white">
                                    dinisurumad@gmail.com</a>

                              </li>
                            </ul>
                          </div>
                        </div>
                      </div>
                      <div className="w-full mt-10 py-10 border-t border-zinc-200 font-inter text-center text-xs text-zinc-400">
                          Copyright © 2024   All rights reserved.
                      </div>

                      
                    </div>
              </footer>

        



        
        

      </main> 


    </div>

      
  
  );
}
